In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
%cd "/content/drive/My Drive/sentiment_analysis/sentiment_analysis"

/content/drive/My Drive/sentiment_analysis/sentiment_analysis


In [0]:
#This cell imports APEX for using GPU
%cd "/content/drive/My Drive/sentiment_analysis/"
#Download Pytorch with proper version
!pip install https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl && pip install https://download.pytorch.org/whl/cu100/torchvision-0.4.0-cp36-cp36m-manylinux1_x86_64.whl
# !git clone https://github.com/NVIDIA/apex
!pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./apex
# !cd apex && pip install -v --no-cache-dir --cuda_ext ./
%cd "/content/drive/My Drive/sentiment_analysis/sentiment_analysis"

/content/drive/My Drive/sentiment_analysis
     |████████████████████████████████| 748.9MB 18kB/s 
ERROR: torchvision 0.4.2 has requirement torch==1.3.1, but you'll have torch 1.2.0 which is incompatible.
  Found existing installation: torch 1.3.1
    Uninstalling torch-1.3.1:
      Successfully uninstalled torch-1.3.1
     |████████████████████████████████| 8.8MB 5.4MB/s 
  Found existing installation: torchvision 0.4.2
    Uninstalling torchvision-0.4.2:
      Successfully uninstalled torchvision-0.4.2
/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py:283: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Created temporary directory: /tmp/pip-ephem-wheel-cache-45jeyshu
Created temporary directory: /tmp/pip-req-tracker-qk31bpue
Created requirements tracker '/tmp/pip-req-tracker-qk31bpue'
Created temporary directory: /tmp/pip-install-vrrgm3ep
Processi

In [0]:
# run only first time to get repo
import os, subprocess
from getpass import getpass
import urllib

user = input('User name: ')
password = getpass('Password: ')
password = urllib.parse.quote(password) # your password is converted into url format

!git clone https://{user}:{password}@github.com/wangobango/sentiment_analysis.git
cmd_string, password = "", ""

User name: Loqaritm
Password: ··········
Cloning into 'sentiment_analysis'...
remote: Enumerating objects: 224, done.
remote: Counting objects: 100% (224/224), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 678 (delta 129), reused 195 (delta 104), pack-reused 454
Receiving objects: 100% (678/678), 17.76 MiB | 12.70 MiB/s, done.
Resolving deltas: 100% (391/391), done.


In [0]:
# needs to be rerun every time
!pip3 install -r requirements.txt

     |████████████████████████████████| 19.1MB 162kB/s 
     |████████████████████████████████| 61kB 10.0MB/s 
     |████████████████████████████████| 5.8MB 37.0MB/s 
     |████████████████████████████████| 1.5MB 48.6MB/s 
     |████████████████████████████████| 20.0MB 162kB/s 
     |████████████████████████████████| 51kB 8.9MB/s 
     |████████████████████████████████| 7.0MB 37.5MB/s 
     |████████████████████████████████| 25.2MB 1.2MB/s 
     |████████████████████████████████| 51.5MB 59kB/s 
  Created wheel for autocorrect: filename=autocorrect-0.4.4-cp36-none-any.whl size=19134813 sha256=c171f98352f7c0404aa8386eea2fdc7a6eb0719b3a0a781a9ebbd3896e4523d5
  Stored in directory: /root/.cache/pip/wheels/e5/80/6d/feed99c22f3f15b0b6881569dc9021f7e94b6464aa0688d819
  Created wheel for console-progressbar: filename=console_progressbar-1.1.2-cp36-none-any.whl size=4141 sha256=6400de4c6143083dfdc72234d69c2a23badff39b025d58182813fee72a206cf4
  Stored in directory: /root/.cache/pip/wheels/35/48/

In [0]:
# Only the first time
!chmod +x download_dataset.sh
!python3 setup.py

In [0]:
# Rerun every time
!pip install transformers
!pip install tensorboardx
!pip install simpletransformers

In [0]:
import pandas as pd
import logging, pickle, sys
from simpletransformers.classification import ClassificationModel
from utils.data_reader import DataReader

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [0]:
LOGGER = logging.getLogger("SimpleTranformers")
LABEL_MAP = {'negative': int(0), 'positive': int(1)}

def readSets(amount=None):
    dataReader = DataReader()
    train_df = dataReader.read_data_set(False)
    train_df = train_df[train_df['text'] != ""]
    if amount is not None:
        train_df = train_df[:amount]
    eval_df = dataReader.read_test_set(False)
    eval_df = eval_df[eval_df['text'] != ""]
    if amount is not None:
        eval_df = eval_df[:amount]
    return train_df, eval_df

def adjustSets(train_df, eval_df):
    train_df = pd.DataFrame({
        'text': train_df['text'].replace(r'\n', ' ', regex=True),
        'label':train_df['polarity'].replace(LABEL_MAP)
    })
    eval_df = pd.DataFrame({
        'text': eval_df['text'].replace(r'\n', ' ', regex=True),
        'label':eval_df['polarity'].replace(LABEL_MAP)
    })
    train_df['text'] = train_df['text'].astype(str)
    eval_df['text'] = eval_df['text'].astype(str)
    return train_df, eval_df

In [0]:
# read data
train_df, eval_df = readSets()
train_df, eval_df = adjustSets(train_df, eval_df)
print(train_df.head())
print(eval_df.head())

                                                text  label
0                                            Length:      1
1  Bought at Toys r Us for 8 year old. Had fun pu...      0
2  This movie was a waste of time. Pointless.Cert...      0
3  I want to preface this review by letting the r...      0
4  I bought this @ 0ffice Depot...good thing. The...      0
                                                text  label
0  Another unbelievably brilliant album from tech...      1
1  OK so it almost 2006 and this last weekend I a...      1
2  I don't like RPG's where you only control one ...      0
3  This book is very good but it needs some more ...      0
4  After 6 minutes any south park show I download...      0


In [0]:
# load model
# overwrite - nadpisz output
overwrite = False
# reprocess - przy zmianie modelu lub danych, wtedy nie wykorzysta cachowanych
reprocess = True

# Create a TransformerModel
model = ClassificationModel('bert', 'bert-base-cased', use_cuda = True, args={'num_train_epochs': 10, 'overwrite_output_dir' : overwrite, 'reprocess_input_data': reprocess, 'logging_steps':2000, 'save_steps':20000})

In [0]:
# reloading model
model = ClassificationModel('bert', 'simpletransformers/outputs/epoch-3', use_cuda = True, args={'overwrite_output_dir': False, 'reprocess_input_data': True, 'output_dir': 'simpletransformers/outputs/epoch-4_new'})

In [0]:
# Train the model
# jakby co Emil to jest maszyna stanów i ona zapamiętuje argsy które podałeś przy tworzeniu, ale jak chcesz je zmienić to możesz podać przy trenowaniu to nadpisze
# wiec jakby co nie trzeba podawac dwa razy

model.train_model(train_df, output_dir='simpletransformers/outputs/epoch-4_new', args={'overwrite_output_dir' : False, 'logging_steps':2000, 'save_steps':20000}, show_running_loss=False )

/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py:291: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


Converting to features started. Cache is not used.



Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic


/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:73: UserWarning: Seems like `optimizer.step()` has been overridden after learning rate scheduler initialization. Please, make sure to call `optimizer.step()` before `lr_scheduler.step()`. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)


Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 8192.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 4096.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 4096.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 2048.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 1024.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 1024.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 512.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 256.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 128.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 64.0
Gradient overflow.  Skipping step, loss scaler 0 reduci

In [0]:
# Evaluate the model
result, model_outputs, wrong_predictions = model.eval_model(eval_df)

/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py:686: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


Features loaded from cache at cache_dir/cached_dev_bert_128_2_300000


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:896: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


In [0]:
from utils.data_evaluator import Evaluator

trueValues = eval_df['label']
trueValues = trueValues.to_numpy()
trueValues = 1 - trueValues
print(trueValues)

# rows = train_df.head()
rows = eval_df['text']

outputs, dupa = model.predict(rows)
print(outputs)

evaluator = Evaluator()
metrics = evaluator.evaluate(trueValues, outputs)
print(metrics)

[0 1 0 ... 0 1 0]
Converting to features started. Cache is not used.


[1 0 1 ... 1 1 1]
accuracy: 0.18029666666666666
precision: 0.24727941525213826	recall: 0.31282
f-score: 0.2762150595867046
{'accuracy': 0.18029666666666666, 'precision': 0.24727941525213826, 'recall': 0.31282, 'f-score': 0.2762150595867046}


In [0]:
#epoch 1
from utils.data_evaluator import Evaluator

trueValues = eval_df['label']
trueValues = trueValues.to_numpy()
# trueValues = 1 - trueValues
print(trueValues)

# rows = train_df.head()
rows = eval_df['text']

outputs, dupa = model.predict(rows)
print(outputs)

evaluator = Evaluator()
metrics = evaluator.evaluate(trueValues, outputs)
print(metrics)

[1 0 1 ... 1 0 1]
Features loaded from cache at cache_dir/cached_dev_bert_128_2_300000


[1 0 1 ... 1 1 1]
accuracy: 0.8197033333333333
precision: 0.7527205847478617	recall: 0.9522266666666667
f-score: 0.8408009253672477
{'accuracy': 0.8197033333333333, 'precision': 0.7527205847478617, 'recall': 0.9522266666666667, 'f-score': 0.8408009253672477}


In [0]:
#epoch 2
trueValues = eval_df['label']
trueValues = trueValues.to_numpy()
# trueValues = 1 - trueValues
print(trueValues)

# rows = train_df.head()
rows = eval_df['text']

outputs, dupa = model.predict(rows)
print(outputs)

evaluator = Evaluator()
metrics = evaluator.evaluate(trueValues, outputs)
print(metrics)

[1 0 1 ... 1 0 1]
Features loaded from cache at cache_dir/cached_dev_bert_128_2_300000


[1 0 1 ... 1 0 1]
accuracy: 0.86373
precision: 0.8790828556539865	recall: 0.84348
f-score: 0.8609134983414136
{'accuracy': 0.86373, 'precision': 0.8790828556539865, 'recall': 0.84348, 'f-score': 0.8609134983414136}


In [0]:
#epoch 3
trueValues = eval_df['label']
trueValues = trueValues.to_numpy()
# trueValues = 1 - trueValues
print(trueValues)

# rows = train_df.head()
rows = eval_df['text']

outputs, dupa = model.predict(rows)
print(outputs)

evaluator = Evaluator()
metrics = evaluator.evaluate(trueValues, outputs)
print(metrics)

[1 0 1 ... 1 0 1]
Features loaded from cache at cache_dir/cached_dev_bert_128_2_300000


[1 0 1 ... 1 0 1]
accuracy: 0.8755533333333333
precision: 0.886976891160388	recall: 0.8607933333333333
f-score: 0.8736889827182547
{'accuracy': 0.8755533333333333, 'precision': 0.886976891160388, 'recall': 0.8607933333333333, 'f-score': 0.8736889827182547}
